SOURCES += \
    gtfo_tests/static/static_test_are_addable.cpp \
    gtfo_tests/static/static_test_are_multipliable.cpp \
    gtfo_tests/static/static_test_are_subtractable.cpp \
    gtfo_tests/static/static_test_common_type_2.cpp \
    gtfo_tests/static/static_test_has_begin.cpp \
    gtfo_tests/static/static_test_has_end.cpp \
    gtfo_tests/static/static_test_is_assignable.cpp \
    gtfo_tests/static/static_test_is_dereferenceable.cpp \
    gtfo_tests/static/static_test_is_equality_comparable.cpp \
    gtfo_tests/static/static_test_can_be_used_in_boolean_context.cpp \
    gtfo_tests/static/static_test_is_range.cpp \
    gtfo_tests/static/static_test_is_range_castable_to_its_iterator.cpp \
    gtfo_tests/static/static_test_is_incrementable.cpp \
    gtfo_tests/static/static_test_is_invokable_fun0.cpp \
    gtfo_tests/static/static_test_is_invokable_fun1.cpp \
    gtfo_tests/static/static_test_is_invokable_fun2.cpp \
    gtfo_tests/static/static_test_is_iterator.cpp \
    gtfo_tests/static/static_test_iterator_of_range.cpp \
    gtfo_tests/static/static_test_result_of_addition.cpp \
    gtfo_tests/static/static_test_result_of_multiplication.cpp \
    gtfo_tests/static/static_test_result_of_subtraction.cpp \
    gtfo_tests/static/static_test_result_of_begin.cpp \
    gtfo_tests/static/static_test_result_of_end.cpp \
    gtfo_tests/static/static_test_result_of_dereferencing.cpp \
    gtfo_tests/static/static_test_result_of_fun0.cpp \
    gtfo_tests/static/static_test_result_of_fun1.cpp \
    gtfo_tests/static/static_test_result_of_fun2.cpp \
    gtfo_tests/static/static_test_result_of_range_iterator_dereferencing.cpp \
    gtfo_tests/static/static_test_value_from_range.cpp \
    gtfo_tests/static/static_test_value_of_dereferenced.cpp \
    gtfo_tests/static/static_test_is_range_with_same_begin_end.cpp \
    gtfo_tests/runtime/numeric/runtime_test_accumulate.cpp \
    gtfo_tests/runtime/numeric/runtime_test_adjacent_difference.cpp \
    gtfo_tests/runtime/numeric/runtime_test_inner_product.cpp \
    gtfo_tests/runtime/numeric/runtime_test_partial_sum.cpp \
    gtfo_tests/runtime/numeric/runtime_test_iota.cpp \
    gtfo_tests/runtime/algorithm/runtime_test_for_each.cpp \
    gtfo_tests/runtime/runtime_tests.cpp \
    gtfo_tests/runtime/algorithm/runtime_test_all_of.cpp \
    gtfo_tests/runtime/algorithm/runtime_test_any_of.cpp \
    gtfo_tests/runtime/algorithm/runtime_test_none_of.cpp

gcc: QMAKE_CXXFLAGS += -std=c++11 -Wall -pedantic
msvc: DEFINES += GTFO_MSVC_RUNTIME_TESTS_NO_CIN_GET

HEADERS += \
    gtfo/type_traits.hpp \
    gtfo/numeric.hpp \
    gtfo/numeric/accumulate.hpp \
    gtfo/numeric/adjacent_difference.hpp \
    gtfo/algorithm.hpp \
    gtfo/algorithm/for_each.hpp \
    gtfo/numeric/inner_product.hpp \
    gtfo/_impl/type_traits.hpp \
    gtfo/_impl/type_traits/has_begin.hpp \
    gtfo/_impl/type_traits/has_end.hpp \
    gtfo/_impl/type_traits/result_of_begin.hpp \
    gtfo/_impl/type_traits/result_of_end.hpp \
    gtfo/_impl/type_traits/is_dereferenceable.hpp \
    gtfo/_impl/type_traits/result_of_dereferencing.hpp \
    gtfo/_impl/type_traits/value_of_dereferenced.hpp \
    gtfo/_impl/type_traits/is_equality_comparable.hpp \
    gtfo/_impl/type_traits/is_incrementable.hpp \
    gtfo/_impl/type_traits/is_iterator.hpp \
    gtfo/_impl/type_traits/is_invokable_fun0.hpp \
    gtfo/_impl/type_traits/is_invokable_fun1.hpp \
    gtfo/_impl/type_traits/is_invokable_fun2.hpp \
    gtfo/_impl/type_traits/are_addable.hpp \
    gtfo/_impl/type_traits/are_subtractable.hpp \
    gtfo/_impl/type_traits/are_multipliable.hpp \
    gtfo/_impl/type_traits/result_of_fun0.hpp \
    gtfo/_impl/type_traits/result_of_fun1.hpp \
    gtfo/_impl/type_traits/result_of_fun2.hpp \
    gtfo/_impl/type_traits/result_of_addition.hpp \
    gtfo/_impl/type_traits/result_of_subtraction.hpp \
    gtfo/_impl/type_traits/result_of_multiplication.hpp \
    gtfo/_impl/type_traits/is_assignable.hpp \
    gtfo/_impl/type_traits/common_type_2.hpp \
    gtfo/numeric/partial_sum.hpp \
    gtfo/numeric/iota.hpp \
    gtfo/algorithm/all_of.hpp \
    gtfo/algorithm/any_of.hpp \
    gtfo/_impl/type_traits/can_be_used_in_boolean_context.hpp \
    gtfo/algorithm/none_of.hpp \
    gtfo/_impl/type_traits/is_range.hpp \
    gtfo/_impl/type_traits/is_range_castable_to_its_iterator.hpp \
    gtfo/_impl/type_traits/iterator_of_range.hpp \
    gtfo/_impl/type_traits/value_from_range.hpp \
    gtfo/_impl/type_traits/result_of_range_iterator_dereferencing.hpp \
    gtfo/reversed_range.hpp \
    gtfo/_impl/_common_definitions.hpp \
    gtfo/_impl/type_traits/_type_traits_definitions.hpp \
    gtfo/_impl/utility.hpp \
    gtfo/_impl/type_traits/is_range_with_same_begin_end.hpp \
    gtfo_tests/runtime/runtime_tests.hpp
