#ifndef GTFO_FILE_INCLUDED_TYPE_TRAITS_HPP
#define GTFO_FILE_INCLUDED_TYPE_TRAITS_HPP

#include "gtfo/_impl/type_traits/has_begin.hpp"
#include "gtfo/_impl/type_traits/has_end.hpp"
#include "gtfo/_impl/type_traits/result_of_begin.hpp"
#include "gtfo/_impl/type_traits/result_of_end.hpp"
#include "gtfo/_impl/type_traits/is_dereferenceable.hpp"
#include "gtfo/_impl/type_traits/result_of_dereferencing.hpp"
#include "gtfo/_impl/type_traits/value_of_dereferenced.hpp"
#include "gtfo/_impl/type_traits/can_be_used_in_boolean_context.hpp"
#include "gtfo/_impl/type_traits/is_equality_comparable.hpp"
#include "gtfo/_impl/type_traits/is_incrementable.hpp"
#include "gtfo/_impl/type_traits/is_iterator.hpp"
#include "gtfo/_impl/type_traits/is_container.hpp"
#include "gtfo/_impl/type_traits/iterator_of_container.hpp"
#include "gtfo/_impl/type_traits/value_from_container.hpp"
#include "gtfo/_impl/type_traits/is_invokable_fun0.hpp"
#include "gtfo/_impl/type_traits/is_invokable_fun1.hpp"
#include "gtfo/_impl/type_traits/is_invokable_fun2.hpp"
#include "gtfo/_impl/type_traits/are_addable.hpp"
#include "gtfo/_impl/type_traits/are_subtractable.hpp"
#include "gtfo/_impl/type_traits/are_multipliable.hpp"
#include "gtfo/_impl/type_traits/result_of_fun0.hpp"
#include "gtfo/_impl/type_traits/result_of_fun1.hpp"
#include "gtfo/_impl/type_traits/result_of_fun2.hpp"
#include "gtfo/_impl/type_traits/result_of_addition.hpp"
#include "gtfo/_impl/type_traits/result_of_subtraction.hpp"
#include "gtfo/_impl/type_traits/result_of_multiplication.hpp"
#include "gtfo/_impl/type_traits/is_assignable.hpp"
#include "gtfo/_impl/type_traits/common_type_2.hpp"
#include "gtfo/_impl/type_traits/is_container_castable_to_its_iterator.hpp"
#include "gtfo/_impl/type_traits/result_of_container_iterator_dereferencing.hpp"

#endif // GTFO_FILE_INCLUDED_TYPE_TRAITS_HPP
